#!/bin/sh

if test -e "$HOME"/.config/ublue/firstboot-done; then
    echo "Already ran"
    exit 0
fi

(
echo "# Waiting for Internet connection"
until /usr/bin/ping -q -c 1 flathub.org; do sleep 1; done
echo "00"

echo "# Removing Filtered Flathub Repository"
/usr/bin/flatpak remote-delete flathub --force ||:
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Removing Filtered Flathub Repo Failed"
        exit 1
fi
echo "3"

echo "# Enabling Flathub Repository"
/usr/bin/flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Adding Flathub Repo Failed"
        exit 1
fi
echo "5"

echo "# Replacing Fedora Flatpaks with Flathub Ones (this may take a while)"
/usr/bin/flatpak install --user --noninteractive org.gnome.Platform//43
/usr/bin/flatpak install --user --noninteractive --reinstall flathub $(flatpak list --app-runtime=org.fedoraproject.Platform --columns=application | tail -n +1 )
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Replacing Fedora Flatpaks Failed"
        exit 1
fi
echo "10"

echo "# Removing Fedora Flatpak Repository"
/usr/bin/flatpak remote-delete fedora --force ||:
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Removing Fedora Flatpak Repo Failed"
        exit 1
fi
echo "15"

echo "# Installing Firefox"
/usr/bin/flatpak install --user --noninteractive flathub org.mozilla.firefox
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Firefox Failed"
        exit 1
fi
echo "20"

echo "# Installing Extension Manager"
/usr/bin/flatpak install --user --noninteractive flathub com.mattjakeman.ExtensionManager
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Extension Manager Failed"
        exit 1
fi
echo "25"

echo "# Installing Flatseal"
/usr/bin/flatpak install --user --noninteractive flathub com.github.tchx84.Flatseal
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Flatseal Failed"
        exit 1
fi
echo "30"

echo "# Installing LiveCaptions"
/usr/bin/flatpak install --user --noninteractive flathub net.sapples.LiveCaptions
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing LiveCaptions Failed"
        exit 1
fi
echo "35"

echo "# Installing Gradience"
/usr/bin/flatpak install --user --noninteractive flathub com.github.GradienceTeam.Gradience
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Gradience Failed"
        exit 1
fi
echo "40"

echo "# Installing Smile"
/usr/bin/flatpak install --user --noninteractive flathub it.mijorus.smile
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Smile Failed"
        exit 1
fi
echo "45"

echo "# Installing GdmSettings"
/usr/bin/flatpak install --user --noninteractive flathub io.github.realmazharhussain.GdmSettings
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing GdmSettings Failed"
        exit 1
fi
echo "50"

echo "# Installing Celluloid Media Player"
/usr/bin/flatpak install --user --noninteractive flathub io.github.celluloid_player.Celluloid
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Celluloid Failed"
        exit 1
fi
echo "55"

echo "# Installing Clapper"
/usr/bin/flatpak install --user --noninteractive flathub com.github.rafostar.Clapper
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Clapper Failed"
        exit 1
fi
echo "60"

echo "# Installing DBeaver"
/usr/bin/flatpak install --user --noninteractive flathub io.dbeaver.DBeaverCommunity
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing DBeaver Failed"
        exit 1
fi
echo "65"

echo "# Installing Postman"
/usr/bin/flatpak install --user --noninteractive  install flathub com.getpostman.Postman
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Postman Failed"
        exit 1
fi
echo "65"

echo "# Installing Flameshot"
/usr/bin/flatpak install --user --noninteractive flathub org.flameshot.Flameshot
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Flameshot Failed"
        exit 1
fi
echo "70"

echo "# Installing CopyQ"
/usr/bin/flatpak install --user --noninteractive flathub com.github.hluk.copyq
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing CopyQ Failed"
        exit 1
fi
echo "75"

echo "# Installing Fondo"
/usr/bin/flatpak install --user --noninteractive flathub com.github.calo001.fondo
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Fondo Failed"
        exit 1
fi
echo "80"

echo "# Installing FontManager"
/usr/bin/flatpak install --user --noninteractive flathub org.gnome.FontManager
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing FontManager Failed"
        exit 1
fi
echo "85"

echo "# Installing Discord"
/usr/bin/flatpak install --user --noninteractive flathub com.discordapp.Discord
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Discord Failed"
        exit 1
fi
ln -sf $XDG_RUNTIME_DIR/{app/com.discordapp.Discord,}/discord-ipc-0 
mkdir -p ~/.config/user-tmpfiles.d
echo 'L %t/discord-ipc-0 - - - - app/com.discordapp.Discord/discord-ipc-0' > ~/.config/user-tmpfiles.d/discord-rpc.conf
systemctl --user enable --now systemd-tmpfiles-setup.service
echo "90"

echo "# Installing Rust"
curl https://sh.rustup.rs -sSf | sh -s -- -y
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Rust Failed"
        exit 1
fi
echo "95"

echo "# Setting up zsh"
PASSWORD=$(zenity --title="Configure the shell require sudo" --password)
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Password Entry Error"
        exit 1
fi
echo -e "$PASSWORD\n/usr/bin/zsh" | sudo -S lchsh $USER
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Error setting up ZSH"
        exit 1
fi
echo "100"

echo '# Installing NVM'
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
echo -e '\n\nexport NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion' >> .zshrc
echo "100"

echo "# Setting up Docker"
PASSWORD=$(zenity --title="Configure docker require sudo" --password)
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Password Entry Error"
        exit 1
fi
echo "docker:x:998:$USER" | sudo tee -a /etc/group
echo "100"

echo "# Reticulating Final Splines"
mkdir -p "$HOME"/.config/ublue/
touch "$HOME"/.config/ublue/firstboot-done

) | 
     
   zenity --progress --title="uBlue Desktop Firstboot" --percentage=0 --auto-close --no-cancel --width=300

if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Firstboot Configuration Error"
fi
